### ISSUE TITLE
"Not delete" bug

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#1]
Wenn bei Modulen (und vllt auch sonst) Löschen gedrückt wird, bei der Anfrage "Sicher löschen" "Nein" zweimal drücken, klappt das Popup beim zweiten Mal nicht mehr zu.

**Comment by pfaffelh** [comment]
Den Fehler habe ich reproduziert. Wäre mir für den Moment egal, löschen ist sowieso ganz selten.
