### ISSUE TITLE
Konflikt-checker implementieren

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#10]

**Comment by julianwiedermann** [comment]
Man könnte überlegen einen semantischen Konflikt-Checker zu implementieren (z.B. gibt es eine doppelte Raumbuchung). Aufwand/Nutzen-Verhältnis sowie genaue Ausgestaltung unklar.

**Comment by pfaffelh** [comment]
Eine doppelte Raumbuchung wird im Raumplan angezeigt. Könnte man auf Personenseite natürlich auch machen, so dass sich keiner selbst doppelt verbucht. Da finde ich aber jetzt den Aufwand zu hoch...

**Comment by pfaffelh** [comment]
Zu kompliziert...
