### ISSUE TITLE
"Save"-Button at Veranstaltung_edit

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#17]
Only one button at the top which saves all instead of multiple one.

**Comment by julianwiedermann** [comment]
Wenn nur Form gespeichert wird auch darauf hinweisen.
Wenn möglich: "Alles speichern"

**Comment by Tobb2002** [comment]
Neuer Termin wird sofort gespeichert verschwindet nicht wenn man auf Zurück ohne Speichern klickt.

**Comment by Tobb2002** [comment]
Um den "Alles Speichern" Button zu implementieren habe ich st.form im Expander Personen und Kommentiertes Vorlesungsverzeichnis entfernt.
