### ISSUE TITLE
Error bei Semester Kopieren

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#21]
Wenn Semester kopieren und dann Veranstaltungen abwählen (bei Seminaren) taucht TypeError auf.

**Comment by julianwiedermann** [comment]
Außerdem fehlt da ein Abbrechen (o.ä.) Button.

**Comment by julianwiedermann** [comment]
Fehler liegt in Line 88:
df_new = st.data_editor(
            df, height = None, column_config = {"_id": None}, disabled ["Name"], hide_index = True)

**Comment by pfaffelh** [comment]
Den Fehler habe ich nicht verstanden, bzw kann ihn nicht reproduzieren. Was genau muss ich tun?

**Comment by pfaffelh** [comment]
Habe "Semester anlegen" nochmal komplett gecheckt, da war noch etwas zu tun, weil Codekategorie neu ist und nicht korrekt kopiert wurde.
