### ISSUE TITLE
Redundanz Semesterkopieren

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#22]
Kann man die Auswahl, welche Veranstaltung kopiert werden und was davon in eine Tabelle o.ä. packen?

**Comment by pfaffelh** [comment]
Ja, das muss man irgendwie anders machen. Hinzu kommt, dass man typischerweise die Veranstaltungen aus dem vorletzten, die Personen aber aus dem letzten Semester übernehmen will... Da kann ich mal überlegen.

**Comment by pfaffelh** [comment]
Jetzt werden die Veranstaltungen aus dem vorletzten, die Personen und Studiengänge aus dem letzten Semester genommen.
