### ISSUE TITLE
Veranstaltung Menü

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#23]
Spalte Raum hinter Ende (vor Kommentar)

**Comment by julianwiedermann** [comment]
Zeit-Auswahlmenü nur von 8:00 bis 20:00 und nur ganze Stunden, und mehr als drei Anzeigen im DD-Menü.

**Comment by julianwiedermann** [comment]
Zusätzliche Spalte "Personen", optional mit Multi-Auswahl hinzufügen. Soll angezeigt werden in der entsprechenden Zeile, wenn nicht leer.

**Comment by julianwiedermann** [comment]
Speichern-Buttons checken. Wo sind Buttons und was speichern sie?

**Comment by julianwiedermann** [comment]
Art des Termins: Ideal - Auswahlmenü und freie Eingabe. Idee - Bei "Neuer Termin" Pop-Up-Menü, bei dem man vorgefertigte Texte überlegt.
Bei einmaligen Terminen ebenfalls.

**Comment by julianwiedermann** [comment]
> Zeit-Auswahlmenü nur von 8:00 bis 20:00 und nur ganze Stunden, und mehr als drei Anzeigen im DD-Menü.

Ganze Stunden: Done
Start ab 8:00: Geht nicht, Vorschlag "Vorgefüllt" -> Discuss
Mehr als drei: Geht nicht

**Comment by julianwiedermann** [comment]
> Speichern-Buttons checken. Wo sind Buttons und was speichern sie?

Aktuell:
Jeder Speichern-Button speichert seine Form/Expander sonst nichts.
"Press enter to apply" heißt nur, dass es in dem Feld eingetragen ist, aber noch nicht in der Datenbank gespeichert...

**Comment by julianwiedermann** [comment]
> > Zeit-Auswahlmenü nur von 8:00 bis 20:00 und nur ganze Stunden, und mehr als drei Anzeigen im DD-Menü.
> 
> Ganze Stunden: Done Start ab 8:00: Geht nicht, Vorschlag "Vorgefüllt" -> Discuss Mehr als drei: Geht nicht

Vorauswahl 9:00 Uhr vorerst rausnehmen!

**Comment by pfaffelh** [comment]
Noch zu tun: Personenliste für wöchentlichen Termin...

**Comment by pfaffelh** [comment]
Alles fertig.

**Comment by pfaffelh** [comment]
alles fertig
