### ISSUE TITLE
Neues Objekt zweimal hinzufügen

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#26]
Wenn man ein neues Objekt (ausprobiert mit Person und Studiengang) hinzufügt und anschließend auf Zurück ohne Speichern klickt. Kann man keine neuen Objekte mehr hinzufügen:

```
DuplicateKeyError: E11000 duplicate key error collection: vvz.studiengang index: _id_ dup key: { _id: ObjectId('66472770157e480c90516060') }, full error: {'index': 0, 'code': 11000, 'errmsg': "E11000 duplicate key error collection: vvz.studiengang index: _id_ dup key: { _id: ObjectId('66472770157e480c90516060') }", 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('66472770157e480c90516060')}}
```

**Comment by pfaffelh** [comment]
Müsste mit der neuen Zeile 60 in tools.py
util.new[collection].pop("_id", None)
gelöst sein. Problem war, dass mit insert_one ein Objekt eingefügt werden sollte, das schon eine vorhandene id hatte.
