### ISSUE TITLE
Neuer Termin wird sofort gespeichert

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#28]
Neuer Termin wird sofort gespeichert verschwindet nicht wenn man auf Zurück ohne Speichern klickt.

_Originally posted by @Tobb2002 in https://github.com/pfaffelh/mi-vvz/issues/17#issuecomment-2116990445_
            
Wenn man einen neuen Termin erstellt, wird dieser und alle Änderungen die bisher in diesem Form gemacht wurden direkt in die Datenbank geschrieben. Das soll erst passieren wenn auf Speichern geklickt wird.

**Comment by Tobb2002** [comment]
Um Termine erst temporär zu speichern werden diese jetzt in einem dictionary im session_state zwischengespeichert.
Noch zu erledigen:
- [x] Beim Wechseln zu anderer Seite sollten die temporären Daten gelöscht werden
- [x] Position wechseln bei Terminen, die nicht in der Datenbank führt zu Fehler (einfachste Lösung: knöpfe deaktivieren bis zum ersten Speichern)
- [x] Termin entfernen bei Terminen, die nicht in der Datenbank sind funktioniert nicht

**Comment by Tobb2002** [comment]
Aktuell kriegen neue Termine in der Datenbank alle die gleiche id

**Comment by Tobb2002** [comment]
TODO: neu gespeichert Termine machen manchmal komische dinge beim verschieben

**Comment by Tobb2002** [comment]
Termine verschieben nach dem Termin gelöscht wurden funktioniert nicht, da Termine jetzt nach dem entfernen nur nicht mehr angezeigt und erst wenn man auf speichern klickt gelöscht werden.

**Comment by julianwiedermann** [comment]
> * [ ]  Beim Wechseln zu anderer Seite sollten die temporären Daten gelöscht werden

Umgekehrter Vorgang - also Termin löschen, nicht speichern, Seite wechseln - hat kein Bestand wenn man den Termin wieder öffnet.

**Comment by julianwiedermann** [comment]
> Aktuell kriegen neue Termine in der Datenbank alle die gleiche id

Führt dazu, dass mehrere neuen Termine die angelegt wurden bevor gespeichert wurde interferieren. Vermutlich sollte man wie beim Deaktivieren der "move"-Buttons den "Neuer Termin"-Button deaktivieren.

EDIT: Unter der Annahme, dass immer nur ein temporärer Termin speicherbar ist...

**Comment by julianwiedermann** [comment]
> * [x]  Beim Wechseln zu anderer Seite sollten die temporären Daten gelöscht werden

Müssen sie das zwingend oder ist es nicht auch denkbar, dass man die vorerst puffert und man bspw. auf einer anderen Seite was nachgucken kann beim Bearbeiten? Nicht zwingend nötig, aber wenn es sich gerade so in etwa verhält ist es ja vllt auch ganz nett.
Hab das aber noch nicht ganz durchdacht. Ein Punkt dagegen ist: Aktuell ist dem temporären Termin nicht zugeordnet zu welcher Veranstaltung er gehört. Deshalb taucht er auch bei der Bearbeitungsseite anderer Termine auf. Könnte ein Problem sein, könnte aber auch lösbar sein.
--> Sollte mündlich nochmal diskutiert / durchdacht werden.
