### ISSUE TITLE
Kommentiertes VVZ: Vorkenntnisse nützlich + notwendig

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#29]
Im kommentierten Vorlesungsverzeichnis sollen unter Vorkenntnissen unterschieden werden zwischen Nützlichen und Notwendigen.

**Comment by Tobb2002** [comment]
@pfaffelh soll dafür die Datenbank nochmal abgeändert werden?

**Comment by pfaffelh** [comment]
Wer hat denn die Unterscheidung "nützlich/notwendig" vorgeschlagen? Meiner Erinnerung nach war es so, dass wir diese Unterscheidung auflösen wollten. In den aktuellen Ergänzungen gibt es die Unterscheidung auch nicht mehr.

**Comment by pfaffelh** [comment]
Wird momentan nicht umgesetzt
