### ISSUE TITLE
Veranstaltung hinzufügen

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#3]
Es ist nicht offensichtlich, wie eine neue Veranstaltung im jeweiligen Semester hinzugefügt werden kann (wenn es überhaupt geht...)

**Comment by julianwiedermann** [comment]
Button hinzufügen wäre gut.

**Comment by pfaffelh** [comment]
Dazu würde ich die Funktion tools.kopiere_veranstaltung als template verwenden, um kein Feld zu vergessen...

**Comment by pfaffelh** [comment]
Jetzt gibt es ein popover, in dem man neue Veranstaltungen anlegen kann.
