### ISSUE TITLE
Anforderungskategorien können nicht erstellt werden

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#32]
Für Anforderungskategorie kann das Problem noch nicht gelöst werden, da die edit Seite hier fehlt.

_Originally posted by @Tobb2002 in https://github.com/pfaffelh/mi-vvz/issues/2#issuecomment-2139241906_

Aktuell werden Anforderungskategorien in Expandern bearbeitet. Die Funktion tools.new geht davon aus, dass eine Edit Seite existiert und führt deshalb zu einem Fehler. 

@pfaffelh soll die Bearbeitung weiter mit Expandern gemacht werden oder wie bei den Anforderungen eine Edit Seite erstellt werden?

**Comment by Tobb2002** [comment]
TODO: Neue Anforderung und Anforedrungskategorie kann nicht gespeichert werden.

**Comment by pfaffelh** [comment]
Ich sehe das Problem nicht, was wird nicht gespeichert?

**Comment by pfaffelh** [comment]
Alles ok

**Comment by Tobb2002** [comment]
Also bei mir funktioniert aktuell das Speichern nicht, wenn man bei Anforderungen (oder Anforderungskategorien) eine neue erstellt und diese dann abspeichern will.

**Comment by pfaffelh** [comment]
Hast Du die aktuellste Version? Hat sich einiges getan...

**Comment by pfaffelh** [comment]
Bei "Anforderungskategorie" wird die neue Kategorie direkt angelegt. Aber das ist so selten, dass es mir gerade egal ist.

**Comment by Tobb2002** [comment]
Stimmt habe ich übersehen. Mit der aktuellen Version scheint bei mir auch alles zu funktionieren.
