### ISSUE TITLE
Anforderungskategorien schlecht auffindbar

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#33]
Die Anforderungskategorien sind meiner Meinung nach etwas versteckt, unten auf der Anforderungsseite. Um das übersichtlicher machen könnte man entweder eine extra Seite anlegen oder einen Button zum nach unten scrollen.

**Comment by pfaffelh** [comment]
Einen Button fände ich am besten. (Anforderungskategorien wird man sehr selten änern/ergänzen.)
