### ISSUE TITLE
Neue Termine interferieren

### ISSUE THREAD

**Issue by julianwiedermann** [pfaffelh/mi-vvz#34]
Fehler trat auf bei:
1) Neuer Termin erstellen
2) Daten (wie Kommentare) ausfüllen
3) Neuer Termin erstellen (ohne Speichern o.ä. davor)
4) Daten im gleichen Feld ausfüllen
--> Ausgefühlte Daten des ersten neuen Termin springen zum Teil zu dem was beim zweiten neuen Termin ausgefüllt / -wählt wurde.

Unklar weshalb sowas passieren kann und aktuell nicht reproduzierbar -> Low Priority

**Comment by pfaffelh** [comment]
Erst muss der Fehler reproduzierbar sein...
