### ISSUE TITLE
Warnings in the terminal

### ISSUE THREAD

**Issue by Tobb2002** [pfaffelh/mi-vvz#5]

**Comment by pfaffelh** [comment]
Was verbirgt sich hier, ist das noch offen/reproduzierbar?

**Comment by julianwiedermann** [comment]
Zur Dokumentation: Während man streamlit ausgeführt hat und dort unterwegs war, wurden immer wieder verschiedene Warnings im Terminal ausgegeben, die direkt kein Problem verursacht haben, aber es trotzdem wert waren sich ihnen mal zu widmen.

Aktuell scheint das nicht mehr der Fall zu sein, daher kann man das schließen.
